# Generated by Django 3.1.2 on 2020-12-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fono', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('receptor', models.CharField(default='contacto@clavistev.cl', max_length=100)),
                ('estado', models.CharField(default='Recepcionado', max_length=50)),
            ],
        ),
    ]
